### ISSUE TITLE
Causal values interpretation

### ISSUE THREAD

**Issue by nsankar** [salesforce/causalai#3]
Hi, Kindly help with the interpretation of the causal influence values estimated/predicted by the PC timeseries algo..

In the example given in [ this document url](https://opensource.salesforce.com/causalai/latest/tutorials/PC_Algorithm_TimeSeries.html),   the causal parents predicted are  [('5', -3), ('2', -1)] .

How should we interpret these causal strengths? 
For instance, for a target vertex "0", 

1. Would this mean that parent "5" with value -3 has a much weaker causal influence than the parent '2'  with value -1 ?  Does negative values indicate a weaker causal influence ?  

 2. Is there a min-max numeric range for the predicted causal values like -10 to  +10 ? 

Thank you in advance.

**Comment by devansh-arpit** [comment]
Hi nsankar, the list of predicted parents [('5', -3), ('2', -1)] implies that the following nodes are the parents of variable 0:
1. node number 5 at time step t-3 from the current time step t.
2. node number 2 at time step t-1 from the current time step t.
This list does not contain the strength of the causal links. If you are interested in finding the strength of the discovered causal links, you can look at result['value_dict']. It contains a dictionary, where keys are the node names (or IDs), and the corresponding value can be interpreted as the strength of the causal link.
