### ISSUE TITLE
How to use timeseries data for causal discovery 

### ISSUE THREAD

**Issue by Amy-raj** [salesforce/causalai#5]
How can we use timeseries data that is not generated by DataGenerator for causal discovery and causal inference?

**Comment by devansh-arpit** [comment]
Please see the Jupyter notebook tutorials [here](https://github.com/salesforce/causalai/tree/main/tutorials). Alternatively, if you would like to use our user interface, please see the tutorial video [here](https://salesforce-research-staging.herokuapp.com/projects/CausalAI).
