### ISSUE TITLE
Is it okay if we have timeseries data collected in different time intervals?

### ISSUE THREAD

**Issue by Amy-raj** [salesforce/causalai#8]
Is it okay if we have time series data collected in different intervals for causal discovery?

like we have 2 data points collected in the gap of 3 days and next datapoints at 7 days?

**Comment by devansh-arpit** [comment]
that is probably not a good idea because it violates a fundamental causal discovery algorithm assumption that the time series resolution is uniform.

**Comment by Amy-raj** [comment]
Is there any way that we can perform causal discovery on the data for which time resolution is non uniform through this libraray?

**Comment by devansh-arpit** [comment]
@Amy-raj, the current library does not support it. Could you describe your use case and requirement briefly? We might consider it in the near future.

**Comment by Amy-raj** [comment]
suppose we have banking data and several users are making multiple transactions at different times .We can’t force a user to make transactions at equal intervals of time.In this case time resolution can’t be uniform.

**Comment by devansh-arpit** [comment]
@Amy-raj We could try to look into this particular use case involving heterogeneous time series. Could you provide a bit more detail about the problem? For instance, are the variables the transactions from different users, and the goal is to perform causal discovery over these user transactions?

**Comment by Amy-raj** [comment]
Hi @devansh-arpit .I was just giving an example where each user is making multiple transactions.So it will be multidimensional data Each 2D data represents transactions carried out by a user.Our usecase is from a different domain.I have few questions.
Does salesforce causal AI library have GPU support ?
And should we preprocess the data like we do in ml models before using causal discovery and causal inference? Or Standardizing the data arrays is enough?

**Comment by devansh-arpit** [comment]
@Amy-raj, thanks for the clarification. Feel free to share your use case if you are able to do so, and we can look into ways if we are able to provide support for it in our library.

We do not support GPUs for the algorithms in Causal AI. We do however, support multi-processing, which makes some causal discovery and inference algorithms (especially PC for causal discovery) much faster.

Regarding data standardization, for causal discovery, we support modules for standardizing the data (and it is indeed required). Please see any tutorial on causal discovery algorithms for that. For causal inference, you don't need to perform standardization, as it is taken care of internally.

**Comment by Amy-raj** [comment]
Hi.How to fix this issue when performing target ed causal discovery for a dataset.Same error is occurring when multiprocessing is True or False.There are no NAN values present 
![IMG_8180](https://github.com/salesforce/causalai/assets/54168151/30a3855a-8405-460a-ba5d-43224968330e)

**Comment by devansh-arpit** [comment]
As the error suggests, it seems that this error is happening when applying SVD on a matrix derived from the provided data. Unfortunately it's hard to say much without further knowledge. You may try the Linear kernel in the KCI test to check if that works.

**Comment by devansh-arpit** [comment]
As the error suggests, it seems that this error is happening when applying SVD on a matrix derived from the provided data. Unfortunately it's hard to say much without further knowledge. You may try the Linear kernel in the KCI test to check if that works.
