### ISSUE TITLE
Creation of intervention data

### ISSUE THREAD

**Issue by Amy-raj** [salesforce/causalai#9]
How can we create intervention data on real life dataset for causal inference i.e. ATE or CATE?
Do we have to use data generator to create intervention data in this case?
I have obtained the causal graph for the real life dataset.

**Comment by devansh-arpit** [comment]
@Amy-raj It's not clear what you mean by "create intervention data on real life dataset". But assuming you want to perform causal inference, once you have the causal graph, and the data you already have without intervention, you can already perform causal inference. Using the causal inference module, you can specify the intervention variables and their values, along with the target variable (on which you want to measure ATE or CATE). There is no need for the data generator in the process.

**Comment by Amy-raj** [comment]
By real life dataset ,I meant customer data.I ran causal discovery on the tabular dataset and i obtained full causal graph.When i am instantiating CausalInference object by passing the graph ,I am getting assertion error that the causal graph has cycle .How should we obtain ATE in this case?i tried with pc.skeleton.I am getting the same problem

**Comment by devansh-arpit** [comment]
@Amy-raj, Apologies for the delayed response. I just returned from vacation. The reason why you are getting the error saying the causal graph has cycle is likely that there are undirected edges in your causal graph. Any undirected edge is represented in our library as bidirectional edges, which is a cycle. This is especially true for pc.skeleton, as it only returns undirected edges. But it may also be true for the causal graph returned by PC in general, as the PC algorithm is not guaranteed to orient all the edges.

In this case, you will have to manually orient any undirected edges before running causal inference to avoid the error.

**Comment by Amy-raj** [comment]
Hi @devansh-arpit .Can we use value of value_dict to eliminate the cycle ?Suppose we have 1000 as value_dict of f0 to f3 and 2000 as value_dict of f3 to f0,Can we remove link f0 to f3? Is it ok?

Also One thing I want to say that i am not seeing value_dict and pvalue_dict of few features ,although I am seeing these features are present in parents list.This case is very rare.Do you know what could the reason be?

**Comment by devansh-arpit** [comment]
@Amy-raj, value_dict cannot be used to eliminate cycles. For PC with partial correlation, the value_dict contains the correlation value between 2 variables (or their residuals). These correlation values are used to determine whether one variable is statistically independent of the other or not. This test does not provide any information about the directionality of the edge. You may have to use prior knowledge to orient any undirected edges.

In our code, value_dict and pvalue_dict are only stored for nodes which are found to be causally related. For non-existent causal links, we do not store value_dict and pvalue_dict. This is the reason why you don't see them for some features.
